version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: san_thuong_mai_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234567 # Thay đổi mật khẩu tại đây
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
